### ISSUE TITLE
Configuration Issues (Authorization)

### ISSUE THREAD

**Issue by sitehub2009** [celtic-project/wordpress-lti-platform#2]
In setting up the tool I was originally unable to find the default settings which had a lot of the required fields I was looking for, but I'm still unable to find the oAuth URL which is requested by my platform.

**Comment by spvickers** [comment]
Sorry you found it difficult to configure the system - if you have any suggestions for how to make this simpler, please pass them on.

I am not sure what you mean by the "oAuth URL".  If it is the URL used by releases of LTI prior to version 1.3, then this URL should be provided by the tool provider.  If you are using LTI 1.3 then perhaps you are referring to the Authentication request URL.  The details (including this URL) to be passed to a tool provider are shown at the bottom the tool configuration page (provided the plugin has been configured to support LTI 1.3 - see the Administration page in the wiki documentation of this site for more details).

**Comment by sitehub2009** [comment]
Thank you for the speedy reply. Specifically, my LTI Platform is asking for an "Access Token URL (OAuth)" from the tool side. 
We provided the AUthentication URL, which was also requested, but this is something different. Does that ring any bells?

This is for LTI 1.3

**Comment by spvickers** [comment]
Access tokens are requested from platforms when a tool wishes to make a service request.  Since this plugin does not support any LTI services, it does not have an endpoint for providing access tokens.

If there are any services which you would like to see implemented feel free to create a new issue with details of your use case and we can see how much interest there might be for adding it.

**Comment by sitehub2009** [comment]
Per the handy [LTI 1.3 info page](https://docs.blackboard.com/lti/tutorials/implementation-guide) from Blackboard, we need to receive the following from the tool:

OAuth 2 Token URL - the URL of the platform’s OAuth 2 token issuer for use when making LTI service calls, such as for Assignment and Grades, or Names and Roles.
OIDC Auth Request URL - the URL the tool must redirect back to after an OIDC login request. This is part of the OIDC login flow for protecting against CSRF attacks

**Comment by spvickers** [comment]
As per my previous comment, you only need an access token endpoint if the platform supports any LTI services; this plugin does not and hence does not expose an access token endpoint.

The OIDS Auth Request URL is given at the bottom of the tool configuration page with the client ID, deployment ID, etc; it is labelled "Authentication request URL".

**Comment by sitehub2009** [comment]
Can you clarify what platform this plugin supports? Are you saying I cannot connect this to this LTI platform? What does this plugin do?

**Comment by spvickers** [comment]
This plugin allows WordPress to act as an LTI platform.  If you are looking to have WordPress act as an LTI Tool then you should take a look at the LTI Tool plugin (see https://github.com/celtic-project/wordpress-lti).

**Comment by sitehub2009** [comment]
Perhaps I have the wrong language, but we want our WordPress site to display content from a third party. I believe that makes WordPress the Platform and the third party content site a Tool. Is that correct?

**Comment by spvickers** [comment]
Yes, that is correct.  Users authenticate with the platform and then LTI is used to seamlessly connect them to a third-party tool to access content, activities,etc.

**Comment by sitehub2009** [comment]
It's just a bummer we can't make this work. We have basically everything we need to connect to our tool except the oauth link. Do you know if it'd be possible somehow to add that?

**Comment by spvickers** [comment]
The Access Token endpoint (which I assume is the one you are referring to) is only required when a platform supports one or more LTI services, which this plugin currently does not.  If you have a tool which requires the platform to support an LTI service, my suggestion is that you open a new issue for each such service with details of your use case so that a discussion can take place about how it might be implemented and who else has an interest in it.

**Comment by sitehub2009** [comment]
Sorry what do you mean by LTI Services? Are you saying that your plugin only allows us to connect to a specific LTI Tool?

**Comment by spvickers** [comment]
An LTI service is defined in the 1EdTech specs and includes ones such as assignment and grades, and names and role.

**Comment by sitehub2009** [comment]
Okay, I was able to authenticate using this URL: /wp-json/jwt-auth/v1/token

Now we are having trouble passing a custom order ID. It seems your tool uses ID (resource id) but the other software we are connecting with also requires a order_id. This identifies the piece of content being requested. I tried the following without luck:

[lti-platform tool=X id=826f2b44 custom=order_id=XYZ]1[/lti-platform]
[lti-platform tool=X id=826f2b44 custom_order_id=XYZ]1[/lti-platform]
[lti-platform tool=X id=XYZ]1[/lti-platform]

Can you confirm the correct way for me to use this custom value?

**Comment by spvickers** [comment]
All custom parameters are passed with a prefix of "custom_" (as required by the spec); it is not, therefore permitted to pass a parameter with a name of "order_id", just "custom_order_id".  So adding the attribute "custom=order_id=XYZ" should have included a parameter name "custom_order_id" with a value of "XYZ" in the launch message.

**Comment by sitehub2009** [comment]
I'm so confused by your response - can you say it differently? How should this be formed? The value I need to pass is order_id=XYZ

**Comment by spvickers** [comment]
Have you looked at the documentation page at https://github.com/celtic-project/wordpress-lti-platform/wiki/Usage which includes an example of using the custom attribute to a link?

**Comment by sitehub2009** [comment]
I have, so my understanding was that custom=order_id=XYZ would have worked, but it doesn't. Can you please correct me?

**Comment by spvickers** [comment]
Yes, that should have meant that a parameter named "custom_order_id" with a value of "XYZ" was included in the launch message.  How have you checked that it was not?

**Comment by sitehub2009** [comment]
Yes, it seems that the order_id was not being passed through.

**Comment by sitehub2009** [comment]
what does "'state' is invalid." mean?

**Comment by spvickers** [comment]
How do you know "that the order_id was not being passed through"?  Have you checked the message being sent for all the parameters it includes?

**Comment by spvickers** [comment]
Re "what does "'state' is invalid." mean?": where are you seeing this message?  Are you using LTI 1.3?  If so, I suspect it means that the state parameter is not being recognised by your tool - this does not look like a message generated by this plugin.

**Comment by spvickers** [comment]
Sorry for the redundant question, I should have remembered you are using LTI 1.3.  One common cause for a tool not recognising the state value returned to it is when third-party cookies are being blocked.  If you are not already doing so, try opening the tool in a new tab/window to see of that makes any difference.

**Comment by spvickers** [comment]
I just tried adding a "custom=order_id=XYZ" attribute to a link in my own WordPress 6.1.1 instance and the JWT passed to the tool included the claim as expected:
```
"https://purl.imsglobal.org/spec/lti/claim/custom": {
    "order_id": "XYZ"
}
```
I was using version 2.1.0 of the LTI Platform plugin and version 4.10.0 of the ceLTIc LTI Library plugin.

**Comment by spvickers** [comment]
Please re-open this issue if you are still experiencing problems.
