### ISSUE TITLE
How do I change the http to https in the launch url?

### ISSUE THREAD

**Issue by edzai** [celtic-project/wordpress-lti-platform#4]
Hi, I am using the the plugin wordpress-lti-platform and am trying to connect to Moodle. The problem I am facing is that the wordpress plugin is generating http instead of https for the launch url. How do I change the http to https in the launch url?

**Comment by edzai** [comment]
![Screenshot 2023-03-14 at 11 32 24](https://user-images.githubusercontent.com/10413942/224958001-efb6be86-d505-4219-abf2-fb820a799e1c.png)
This is what I get when I launch the LTI tool

**Comment by spvickers** [comment]
The plugin should use whatever URL you enter in the "Launch message URL" field on the tool configuration page.  Check here to make sure you have entered an https URL.

**Comment by edzai** [comment]
Oh no, made a bad mistake, I should have posted the error on the LTI Tool repo. I confused myself and reported the issue on the wrong repo.

**Comment by edzai** [comment]
Wrong repo
